# Generated by Django 4.2 on 2023-05-04 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
