# Generated by Django 4.2 on 2023-05-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videoid', '0002_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=30)),
                ('video_id', models.CharField(max_length=30)),
                ('comment_id', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('author', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
            ],
        ),
    ]
